catalogs:
  backend:
    '@vercel/analytics': ^1.6.1
    '@vercel/speed-insights': ^1.3.1
    babel-plugin-react-compiler: ^19.1.0-rc.3
    feed: ^5.1.0
    next: ^15.5.7
    velite: ^0.2.4
  dev:
    '@commitlint/config-conventional': ^19.8.1
    '@hellolin-eslint/react-config': ^1.3.1
    '@hellolin-eslint/unocss-config': ^1.3.1
    '@hellolin/eslint-config': ^1.3.1
    commitlint: ^19.8.1
    eslint: ^9.39.1
    execa: ^9.6.1
    husky: ^9.1.7
    lint-staged: ^16.2.7
    npm-run-all: ^4.1.5
  frontend:
    '@expressive-code/plugin-collapsible-sections': ^0.41.3
    '@expressive-code/plugin-line-numbers': ^0.41.3
    '@iconify-json/lucide': ^1.2.78
    '@iconify-json/simple-icons': ^1.2.61
    '@unocss/postcss': ^66.5.10
    '@unocss/preset-icons': ^66.5.10
    '@unocss/preset-wind3': ^66.5.10
    '@unocss/reset': ^66.5.10
    clsx: ^2.1.1
    es-toolkit: ^1.42.0
    katex: ^0.16.25
    next-themes: ^0.4.6
    postcss: ^8.5.6
    postcss-nesting: ^13.0.2
    radix-ui: ^1.4.3
    react: ^19.2.1
    react-dom: ^19.2.1
    rehype-expressive-code: ^0.41.3
    rehype-external-links: ^3.0.0
    rehype-katex: ^7.0.1
    rehype-pretty-code: ^0.14.1
    rehype-slug: ^6.0.0
    remark-emoji: ^5.0.2
    remark-math: ^6.0.0
    shiki: ^3.19.0
    unocss: ^66.5.10
  types:
    '@types/node': ^22.19.1
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    typescript: 5.8.3
