catalogs:
  backend:
    babel-plugin-react-compiler: ^19.1.0-rc.3
    feed: ^5.1.0
    next: ^15.5.4
    velite: ^0.2.4
  dev:
    '@commitlint/config-conventional': ^19.8.1
    '@hellolin-eslint/react-config': ^1.2.0
    '@hellolin-eslint/unocss-config': ^1.2.0
    '@hellolin/eslint-config': ^1.2.0
    commitlint: ^19.8.1
    eslint: ^9.37.0
    execa: ^9.6.0
    husky: ^9.1.7
    lint-staged: ^16.2.3
    npm-run-all: ^4.1.5
  frontend:
    '@expressive-code/plugin-collapsible-sections': ^0.41.3
    '@expressive-code/plugin-line-numbers': ^0.41.3
    '@iconify-json/lucide': ^1.2.68
    '@iconify-json/simple-icons': ^1.2.54
    '@unocss/postcss': ^66.5.2
    '@unocss/preset-icons': ^66.5.2
    '@unocss/preset-wind3': ^66.5.2
    '@unocss/reset': ^66.5.2
    clsx: ^2.1.1
    es-toolkit: ^1.39.10
    katex: ^0.16.23
    next-themes: ^0.4.6
    postcss: ^8.5.6
    postcss-nesting: ^13.0.2
    radix-ui: ^1.4.3
    react: ^19.2.0
    react-dom: ^19.2.0
    rehype-expressive-code: ^0.41.3
    rehype-external-links: ^3.0.0
    rehype-katex: ^7.0.1
    rehype-pretty-code: ^0.14.1
    rehype-slug: ^6.0.0
    remark-emoji: ^5.0.2
    remark-math: ^6.0.0
    shiki: ^3.13.0
    unocss: ^66.5.2
  types:
    '@types/node': ^22.18.8
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    # `@typescript-eslint/parser` doesn't support TS 5.9 yet.
    # https://github.com/eslint-stylistic/eslint-stylistic/issues/915
    # typescript: ^5.9.2
    typescript: 5.8.3
